import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { ScannerAccountRepository } from '../repositories/scannerAccount.repository.js';
import { prisma } from '../../../config/prisma.js';
import { env } from '../../../config/env.js';
import { AppError } from '../../../utils/AppError.js';
import { HTTP_STATUS } from '../../../constants/httpStatusCodes.js';

export class ScannerService {
  /**
   * Event Organizer creates dedicated Scanner Staff credentials for an event
   */
  static async createScanner(organizerId, eventId, dto) {
    // 1. Verify Event Ownership
    const event = await prisma.event.findFirst({
      where: { id: eventId, organizerId },
    });
    if (!event) {
      throw new AppError('Event not found or unauthorized access', HTTP_STATUS.FORBIDDEN);
    }

    // 2. Check if email already exists for this event
    const existing = await ScannerAccountRepository.findByEventAndEmail(eventId, dto.scannerEmail);
    if (existing) {
      throw new AppError('A scanner account with this email already exists for this event', HTTP_STATUS.CONFLICT);
    }

    // 3. Hash Password
    const salt = await bcrypt.genSalt(10);
    const passwordHash = await bcrypt.hash(dto.password, salt);

    // 4. Create Scanner Account
    const scanner = await ScannerAccountRepository.createScannerAccount({
      eventId,
      organizerId,
      scannerName: dto.scannerName,
      scannerEmail: dto.scannerEmail,
      passwordHash,
      assignedSectionIds: dto.assignedSectionIds || [],
      assignedGateIds: dto.assignedGateIds || [],
    });

    const { passwordHash: _, ...safeScanner } = scanner;
    return safeScanner;
  }

  /**
   * Scanner Staff login with email & password generated by Event Planner
   */
  static async authenticateScanner(dto) {
    const scanner = dto.eventId
      ? await ScannerAccountRepository.findByEventAndEmail(dto.eventId, dto.scannerEmail)
      : await ScannerAccountRepository.findByEmailGlobal(dto.scannerEmail);

    if (!scanner || !scanner.isActive) {
      throw new AppError('Invalid credentials or inactive scanner account', HTTP_STATUS.UNAUTHORIZED);
    }

    const isMatch = await bcrypt.compare(dto.password, scanner.passwordHash);
    if (!isMatch) {
      throw new AppError('Invalid credentials', HTTP_STATUS.UNAUTHORIZED);
    }

    const token = jwt.sign(
      {
        scannerAccountId: scanner.id,
        eventId: scanner.eventId,
        organizerId: scanner.organizerId,
        scannerEmail: scanner.scannerEmail,
        scannerName: scanner.scannerName,
        assignedSectionIds: scanner.assignedSectionIds,
        assignedGateIds: scanner.assignedGateIds,
        role: 'SCANNER_STAFF',
      },
      env.JWT_ACCESS_SECRET,
      { expiresIn: '24h' }
    );

    const { passwordHash: _, ...safeScanner } = scanner;
    return {
      token,
      scanner: {
        ...safeScanner,
        eventId: scanner.eventId,
        eventTitle: scanner.event?.title || null,
      },
    };
  }

  /**
   * Fetch all scanner accounts created by Organizer for an Event
   */
  static async getEventScanners(organizerId, eventId) {
    const event = await prisma.event.findFirst({
      where: { id: eventId, organizerId },
    });
    if (!event) {
      throw new AppError('Event not found or unauthorized access', HTTP_STATUS.FORBIDDEN);
    }

    const scanners = await ScannerAccountRepository.findByEvent(eventId);
    
    // Fetch section names mapped to assignedSectionIds
    const sections = await prisma.eventSection.findMany({
      where: { eventId },
      select: { id: true, name: true },
    });
    const sectionMap = new Map(sections.map((s) => [s.id, s.name]));

    return scanners.map((s) => {
      const { passwordHash: _, ...rest } = s;
      return {
        ...rest,
        assignedSectionNames: s.assignedSectionIds.map((id) => sectionMap.get(id) || id),
      };
    });
  }

  /**
   * Update Scanner Account
   */
  static async updateScanner(organizerId, scannerId, dto) {
    const scanner = await ScannerAccountRepository.findById(scannerId);
    if (!scanner || scanner.event.organizerId !== organizerId) {
      throw new AppError('Scanner account not found or unauthorized', HTTP_STATUS.NOT_FOUND);
    }

    const updateData = {};
    if (dto.scannerName) updateData.scannerName = dto.scannerName;
    if (dto.assignedSectionIds) updateData.assignedSectionIds = dto.assignedSectionIds;
    if (dto.assignedGateIds) updateData.assignedGateIds = dto.assignedGateIds;
    if (dto.isActive !== undefined) updateData.isActive = dto.isActive;

    if (dto.password) {
      const salt = await bcrypt.genSalt(10);
      updateData.passwordHash = await bcrypt.hash(dto.password, salt);
    }

    const updated = await ScannerAccountRepository.updateScannerAccount(scannerId, updateData);
    const { passwordHash: _, ...safeScanner } = updated;
    return safeScanner;
  }

  /**
   * Delete Scanner Account
   */
  static async deleteScanner(organizerId, scannerId) {
    const scanner = await ScannerAccountRepository.findById(scannerId);
    if (!scanner || scanner.event.organizerId !== organizerId) {
      throw new AppError('Scanner account not found or unauthorized', HTTP_STATUS.NOT_FOUND);
    }

    await ScannerAccountRepository.deleteScannerAccount(scannerId);
    return { message: 'Scanner account deleted successfully' };
  }

  /**
   * Event Planner Dashboard Metrics: Scanner Accounts Scans & Section Checkin Progress
   */
  static async getDashboardScannerMetrics(organizerId, eventId) {
    const event = await prisma.event.findFirst({
      where: { id: eventId, organizerId },
      include: {
        sections: true,
        scannerAccounts: true,
      },
    });
    if (!event) {
      throw new AppError('Event not found or unauthorized', HTTP_STATUS.FORBIDDEN);
    }

    // 1. Total Tickets and Check-ins Stats
    const totalBookings = await prisma.booking.count({
      where: { eventId, paymentStatus: 'Paid' },
    });

    const totalTicketsCount = await prisma.ticket.count({
      where: { booking: { eventId, paymentStatus: 'Paid' } },
    });

    const totalCheckedInCount = await prisma.ticket.count({
      where: {
        booking: { eventId },
        status: 'CHECKED_IN',
      },
    });

    // 2. Scanners Breakdown Metrics
    const scannersBreakdown = event.scannerAccounts.map((scanner) => ({
      scannerAccountId: scanner.id,
      scannerName: scanner.scannerName,
      scannerEmail: scanner.scannerEmail,
      assignedSectionIds: scanner.assignedSectionIds,
      isActive: scanner.isActive,
      totalScans: scanner.totalScansCount,
      lastScanAt: scanner.lastScanAt,
    }));

    // 3. Sections Breakdown Metrics
    const sectionsBreakdown = await Promise.all(
      event.sections.map(async (sec) => {
        const checkedInInSection = await prisma.checkInLog.count({
          where: {
            eventId,
            sectionId: sec.id,
            scanResult: 'SUCCESS',
          },
        });

        const totalSectionTickets = await prisma.bookingItem.count({
          where: { sectionId: sec.id },
        });

        const percentage = totalSectionTickets > 0 ? (checkedInInSection / totalSectionTickets) * 100 : 0;

        return {
          sectionId: sec.id,
          sectionName: sec.name,
          capacity: sec.capacity,
          totalTicketsIssued: totalSectionTickets,
          checkedInCount: checkedInInSection,
          remainingCount: Math.max(0, totalSectionTickets - checkedInInSection),
          occupancyPercentage: parseFloat(percentage.toFixed(2)),
        };
      })
    );

    return {
      eventId,
      summary: {
        totalTicketsIssued: totalTicketsCount,
        totalCheckedIn: totalCheckedInCount,
        totalRemaining: Math.max(0, totalTicketsCount - totalCheckedInCount),
        overallCheckinPercentage: totalTicketsCount > 0 ? parseFloat(((totalCheckedInCount / totalTicketsCount) * 100).toFixed(2)) : 0,
        activeScannerAccountsCount: event.scannerAccounts.filter((s) => s.isActive).length,
      },
      scannersBreakdown,
      sectionsBreakdown,
    };
  }
}
