import React, { useState, useEffect, useCallback } from 'react';
import { MapPin, Pencil, Trash2, CheckCircle, XCircle, Building2, Calendar } from 'lucide-react';
import { C } from '../../constants/theme.js';
import { cityService } from '../../services/admin/cityService.js';
import { useToast } from '../../hooks/useToast.js';
import { Modal } from '../../components/common/Modal.jsx';
import { MasterDataHeader } from '../../components/admin/MasterDataHeader.jsx';
import { formatDate } from '../../utils/formatters.js';

// ── City form ──────────────────────────────────────────────
/**
 * City schema fields (verified from admin.validator.js + schema.prisma):
 *   name     string (required, unique)
 *   slug     auto-generated by backend
 *   state    string (optional)
 *   country  string (default "India")
 *   isActive boolean (for updates only)
 */
function CityForm({ initial = {}, loading, onSubmit, onCancel }) {
  const [form, setForm] = useState({
    name: initial.name || '',
    state: initial.state || '',
    country: initial.country || 'India',
    isActive: initial.isActive !== undefined ? initial.isActive : true,
  });
  const [errors, setErrors] = useState({});

  const validate = () => {
    const e = {};
    if (!form.name.trim()) e.name = 'City name is required.';
    if (!form.country.trim()) e.country = 'Country is required.';
    return e;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const e2 = validate();
    setErrors(e2);
    if (Object.keys(e2).length) return;
    onSubmit(form);
  };

  const inp = (label, key, opts = {}) => (
    <div style={{ marginBottom: '14px' }}>
      <label style={{ display: 'block', color: C.muted, fontSize: '12px', fontWeight: 600, marginBottom: '5px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
        {label}{opts.required && <span style={{ color: C.red }}> *</span>}
      </label>
      <input
        type="text"
        value={form[key]}
        onChange={(e) => setForm({ ...form, [key]: e.target.value })}
        placeholder={opts.placeholder}
        style={{ width: '100%', background: C.panel, border: `1px solid ${errors[key] ? C.red : C.border}`, borderRadius: '10px', color: C.text, fontSize: '13px', padding: '10px 12px', fontFamily: 'Space Grotesk, sans-serif', outline: 'none', boxSizing: 'border-box' }}
      />
      {errors[key] && <p style={{ color: C.red, fontSize: '11px', margin: '4px 0 0' }}>{errors[key]}</p>}
    </div>
  );

  return (
    <form onSubmit={handleSubmit}>
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
        <div style={{ gridColumn: '1 / -1' }}>{inp('City Name', 'name', { required: true, placeholder: 'e.g. Mumbai' })}</div>
        {inp('State / Province', 'state', { placeholder: 'e.g. Maharashtra' })}
        {inp('Country', 'country', { required: true, placeholder: 'e.g. India' })}
      </div>
      {initial.id && (
        <div style={{ marginBottom: '16px' }}>
          <label style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer' }}>
            <input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })} style={{ width: '16px', height: '16px', cursor: 'pointer', accentColor: C.gold }} />
            <span style={{ color: C.muted, fontSize: '13px' }}>City is <strong style={{ color: form.isActive ? C.green : C.red }}>{form.isActive ? 'Active' : 'Inactive'}</strong></span>
          </label>
        </div>
      )}
      <div style={{ display: 'flex', gap: '10px' }}>
        <button type="button" onClick={onCancel} disabled={loading} style={{ flex: 1, padding: '10px', borderRadius: '10px', border: `1px solid ${C.border}`, background: 'transparent', color: C.muted, cursor: 'pointer', fontFamily: 'Space Grotesk, sans-serif', fontWeight: 600, fontSize: '14px' }}>Cancel</button>
        <button type="submit" disabled={loading} style={{ flex: 1, padding: '10px', borderRadius: '10px', border: `1px solid ${C.borderGold}`, background: C.goldDim, color: C.gold, cursor: loading ? 'not-allowed' : 'pointer', fontFamily: 'Space Grotesk, sans-serif', fontWeight: 700, fontSize: '14px', opacity: loading ? 0.6 : 1 }}>
          {loading ? 'Saving...' : initial.id ? 'Update City' : 'Add City'}
        </button>
      </div>
    </form>
  );
}

function DeleteModal({ city, loading, onConfirm, onCancel }) {
  if (!city) return null;
  return (
    <div style={{ textAlign: 'center' }}>
      <div style={{ width: '52px', height: '52px', borderRadius: '50%', background: C.redDim, border: `1px solid ${C.red}`, display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 16px' }}>
        <Trash2 size={22} color={C.red} />
      </div>
      <h4 style={{ color: C.text, margin: '0 0 8px', fontFamily: 'Space Grotesk, sans-serif', fontSize: '16px' }}>Delete City?</h4>
      <p style={{ color: C.muted, fontSize: '13px', marginBottom: '10px' }}>
        Are you sure you want to delete <strong style={{ color: C.red }}>{city.name}</strong>?
      </p>
      {(city._count?.venues > 0 || city._count?.events > 0) && (
        <div style={{ background: C.amberDim, border: `1px solid ${C.amber}`, borderRadius: '10px', padding: '10px 14px', marginBottom: '14px', fontSize: '12px', color: C.amber }}>
          ⚠️ This city has {city._count?.venues || 0} venue(s) and {city._count?.events || 0} event(s). The backend may reject this deletion.
        </div>
      )}
      <p style={{ color: C.faint, fontSize: '12px', marginBottom: '22px' }}>This action cannot be undone.</p>
      <div style={{ display: 'flex', gap: '10px', justifyContent: 'center' }}>
        <button onClick={onCancel} disabled={loading} style={{ padding: '10px 22px', borderRadius: '10px', border: `1px solid ${C.border}`, background: 'transparent', color: C.muted, cursor: 'pointer', fontFamily: 'Space Grotesk, sans-serif', fontWeight: 600, fontSize: '14px' }}>Cancel</button>
        <button onClick={onConfirm} disabled={loading} style={{ padding: '10px 22px', borderRadius: '10px', border: `1px solid ${C.red}`, background: C.redDim, color: C.red, cursor: loading ? 'not-allowed' : 'pointer', fontFamily: 'Space Grotesk, sans-serif', fontWeight: 700, fontSize: '14px', opacity: loading ? 0.6 : 1 }}>
          {loading ? 'Deleting...' : 'Delete City'}
        </button>
      </div>
    </div>
  );
}

export default function CitiesPage() {
  const { showToast } = useToast();
  const [cities, setCities] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [search, setSearch] = useState('');
  const [actionLoading, setActionLoading] = useState(false);
  const [createOpen, setCreateOpen] = useState(false);
  const [editTarget, setEditTarget] = useState(null);
  const [deleteTarget, setDeleteTarget] = useState(null);

  const fetchCities = useCallback(async () => {
    setLoading(true); setError(null);
    try {
      const res = await cityService.getCities();
      setCities(Array.isArray(res?.data) ? res.data : []);
    } catch (err) {
      setError(err?.message || 'Unable to load cities. Please try again.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchCities(); }, [fetchCities]);

  const filtered = cities.filter((c) => {
    const q = search.toLowerCase();
    return !q || c.name?.toLowerCase().includes(q) || c.state?.toLowerCase().includes(q) || c.country?.toLowerCase().includes(q);
  });

  const stats = [
    { label: 'Total', value: cities.length, color: C.blue, bg: C.blueDim, border: C.borderBlue },
    { label: 'Active', value: cities.filter((c) => c.isActive).length, color: C.green, bg: C.greenDim, border: C.green },
    { label: 'Total Venues', value: cities.reduce((s, c) => s + (c._count?.venues || 0), 0), color: C.gold, bg: C.goldDim, border: C.borderGold },
  ];

  const handleCreate = async (data) => {
    setActionLoading(true);
    try {
      await cityService.createCity(data);
      showToast('City created successfully.', 'success');
      setCreateOpen(false);
      fetchCities();
    } catch (err) { showToast(err?.message || 'Unable to create city.', 'error'); }
    finally { setActionLoading(false); }
  };

  const handleEdit = async (data) => {
    setActionLoading(true);
    try {
      await cityService.updateCity(editTarget.id, data);
      showToast('City updated successfully.', 'success');
      setEditTarget(null);
      fetchCities();
    } catch (err) { showToast(err?.message || 'Unable to update city.', 'error'); }
    finally { setActionLoading(false); }
  };

  const handleDelete = async () => {
    setActionLoading(true);
    try {
      await cityService.deleteCity(deleteTarget.id);
      showToast('City deleted successfully.', 'success');
      setDeleteTarget(null);
      fetchCities();
    } catch (err) { showToast(err?.message || 'Unable to delete city.', 'error'); }
    finally { setActionLoading(false); }
  };

  const col = { padding: '13px 16px', fontSize: '13px', fontFamily: 'Space Grotesk, sans-serif' };

  return (
    <div style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
      <MasterDataHeader
        icon={<MapPin size={18} color={C.gold} />}
        title="City Management"
        subtitle="Manage cities available for events and venues."
        onAdd={() => setCreateOpen(true)}
        addLabel="Add City"
        onRefresh={fetchCities}
        refreshing={loading}
        search={search}
        onSearch={setSearch}
        placeholder="Search by city name, state, or country..."
        showClear={!!search}
        onClear={() => setSearch('')}
        stats={!loading ? stats : []}
      />

      {error && !loading && (
        <div style={{ background: C.redDim, border: `1px solid ${C.red}`, borderRadius: '12px', padding: '16px 20px', marginBottom: '16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span style={{ color: C.red, fontSize: '14px' }}>{error}</span>
          <button onClick={fetchCities} style={{ background: C.red, border: 'none', borderRadius: '8px', color: '#000', padding: '6px 14px', cursor: 'pointer', fontWeight: 700, fontSize: '13px' }}>Retry</button>
        </div>
      )}

      {!loading && !error && (
        <p style={{ color: C.faint, fontSize: '12px', margin: '0 0 12px' }}>
          Showing {filtered.length} of {cities.length} cit{cities.length !== 1 ? 'ies' : 'y'}
          {search && <> matching "<span style={{ color: C.blue }}>{search}</span>"</>}
        </p>
      )}

      <div style={{ borderRadius: '16px', border: `1px solid ${C.border}`, background: C.panel, overflowX: 'auto' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: '700px' }}>
          <thead>
            <tr style={{ background: 'rgba(0,229,255,0.05)', borderBottom: `1px solid ${C.borderBlue}` }}>
              {['City', 'State', 'Country', 'Venues', 'Events', 'Status', 'Created', 'Actions'].map((h) => (
                <th key={h} style={{ padding: '12px 16px', color: C.blue, fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.7px', textAlign: 'left', whiteSpace: 'nowrap' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {loading ? (
              <tr><td colSpan={8} style={{ padding: '50px', textAlign: 'center', color: C.muted }}>
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '12px' }}>
                  <div style={{ width: '28px', height: '28px', border: `2px solid ${C.blue}`, borderTopColor: 'transparent', borderRadius: '50%', animation: 'spin 0.8s linear infinite' }} />
                  Loading cities...
                </div>
              </td></tr>
            ) : filtered.length === 0 ? (
              <tr><td colSpan={8} style={{ padding: '50px', textAlign: 'center', color: C.muted }}>
                <MapPin size={36} color={C.faint} style={{ display: 'block', margin: '0 auto 12px' }} />
                {search ? 'No cities match your search.' : 'No cities found. Click "Add City" to create one.'}
              </td></tr>
            ) : filtered.map((city, idx) => (
              <tr key={city.id} style={{ borderBottom: idx === filtered.length - 1 ? 'none' : `1px solid ${C.border}`, transition: 'background 0.15s' }}
                onMouseEnter={(e) => { e.currentTarget.style.background = 'rgba(255,255,255,0.02)'; }}
                onMouseLeave={(e) => { e.currentTarget.style.background = ''; }}>
                <td style={col}><strong style={{ color: C.blue }}>{city.name}</strong></td>
                <td style={{ ...col, color: C.muted }}>{city.state || <span style={{ color: C.faint, fontStyle: 'italic' }}>—</span>}</td>
                <td style={{ ...col, color: C.muted }}>{city.country}</td>
                <td style={{ ...col, textAlign: 'center' }}>
                  <span style={{ color: C.gold, fontWeight: 700 }}>{city._count?.venues ?? '—'}</span>
                </td>
                <td style={{ ...col, textAlign: 'center' }}>
                  <span style={{ color: C.purple, fontWeight: 700 }}>{city._count?.events ?? '—'}</span>
                </td>
                <td style={col}>
                  {city.isActive
                    ? <span style={{ display: 'inline-flex', alignItems: 'center', gap: '4px', background: C.greenDim, border: `1px solid ${C.green}`, color: C.green, borderRadius: '999px', padding: '3px 10px', fontSize: '11px', fontWeight: 700 }}><CheckCircle size={10} /> Active</span>
                    : <span style={{ display: 'inline-flex', alignItems: 'center', gap: '4px', background: C.redDim, border: `1px solid ${C.red}`, color: C.red, borderRadius: '999px', padding: '3px 10px', fontSize: '11px', fontWeight: 700 }}><XCircle size={10} /> Inactive</span>}
                </td>
                <td style={{ ...col, color: C.faint, fontSize: '12px', whiteSpace: 'nowrap' }}>{formatDate(city.createdAt)}</td>
                <td style={col}>
                  <div style={{ display: 'flex', gap: '6px' }}>
                    <button onClick={() => setEditTarget(city)} style={{ background: C.blueDim, border: `1px solid ${C.borderBlue}`, borderRadius: '8px', color: C.blue, padding: '5px 10px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px', fontSize: '12px', fontWeight: 600 }}>
                      <Pencil size={12} /> Edit
                    </button>
                    <button onClick={() => setDeleteTarget(city)} style={{ background: C.redDim, border: `1px solid ${C.red}`, borderRadius: '8px', color: C.red, padding: '5px 10px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px', fontSize: '12px', fontWeight: 600 }}>
                      <Trash2 size={12} /> Delete
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <Modal isOpen={createOpen} onClose={() => setCreateOpen(false)} title="Add City">
        <CityForm loading={actionLoading} onSubmit={handleCreate} onCancel={() => setCreateOpen(false)} />
      </Modal>
      <Modal isOpen={!!editTarget} onClose={() => setEditTarget(null)} title={`Edit: ${editTarget?.name || ''}`}>
        {editTarget && <CityForm initial={editTarget} loading={actionLoading} onSubmit={handleEdit} onCancel={() => setEditTarget(null)} />}
      </Modal>
      <Modal isOpen={!!deleteTarget} onClose={() => setDeleteTarget(null)} title="Confirm Deletion">
        <DeleteModal city={deleteTarget} loading={actionLoading} onConfirm={handleDelete} onCancel={() => setDeleteTarget(null)} />
      </Modal>

      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
